version: '3'
services:
  mongo:
    image: mongo:5
    volumes:
      - db-data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
      - MONGO_INITDB_DATABASE=wind
      - MONGO_INITDB_USER=wind
      - MONGO_INITDB_PASSWORD=wind
    healthcheck:
      test:
        [
          "CMD",
          "mongo",
          "--eval",
          "db.getSiblingDB('wind').collectionNames()"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
  backend:
    build:
      context: .
      dockerfile: ./package/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - COMMON__DEBUG=false
      - DATABASE__DSN=mongodb://wind:wind@mongo:27017
      - DATABASE__NAME=wind
      - DATABASE__DEBUG=false
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  db-data:
