version: '3'
services:
  nginx:
    image: nginx:1-alpine
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  mongo:
    image: mongo:5
    volumes:
      - db-data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.getSiblingDB('admin')" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  backend:
    image: capcom6/wind:latest
    environment:
      - PORT=8000
      - COMMON__DEBUG=false
      - DATABASE__DSN=mongodb://wind:wind@mongo:27017
      - DATABASE__NAME=wind
      - DATABASE__DEBUG=false
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  db-data:
